server:
  #port: 8000
  #port: 8686
  port: 8787
  
spring:
  application:
    name: VEHICLE-MS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deloitte_db
    username: root
    password: root
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
